name: futurebot
favicon: null
layout_spectrum: 0.5965502324979752
typography_spectrum: 0.5189877573866397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9534884609747678
  lightness: 0.33053914667107165
  saturation: 0.7131770486012101
  rhythmicContrast: 0.8431718978099525
purpose: []
